### ISSUE TITLE
autoreload only reloads once

### ISSUE THREAD

**Issue by alecklandgraf** [skoczen/polytester#11]
`polytester --autoreload` only reloads once then stops retesting.

using `polytester==1.1.2` and python `2.7.3` and have #8 merged in to work.
my tests.yml:

```yaml
backend:
    command: python manage.py test
    watch_glob: "*.py"
    watch_dir: "auditron"
```

If upgrading to python 2.7.8 wouldn't break all my virtualenvs etc, I'd give it a shot. 

I just checked and *watchdog* seems to be working ok:

```console
 $ watchmedo log --patterns="*.py;*.txt" --ignore-directories --recursive .
on_modified(self=<watchdog.tricks.LoggerTrick object at 0x107647590>, event=<FileModifiedEvent: src_path='./auditron/management/commands/setup_auditor_demo.py'>)
on_modified(self=<watchdog.tricks.LoggerTrick object at 0x107647590>, event=<FileModifiedEvent: src_path='./auditron/management/commands/setup_auditor_demo.py'>)
on_modified(self=<watchdog.tricks.LoggerTrick object at 0x107647590>, event=<FileModifiedEvent: src_path='./auditron/management/commands/setup_auditor_demo.py'>)
on_modified(self=<watchdog.tricks.LoggerTrick object at 0x107647590>, event=<FileModifiedEvent: src_path='./auditron/management/commands/setup_auditor_demo.py'>)
on_modified(self=<watchdog.tricks.LoggerTrick object at 0x107647590>, event=<FileModifiedEvent: src_path='./auditron/tests/test_create_default_user.py'>)
on_modified(self=<watchdog.tricks.LoggerTrick object at 0x107647590>, event=<FileModifiedEvent: src_path='./auditron/tests/test_create_default_user.py'>)
```

**Comment by alecklandgraf** [comment]
just upgraded to python `2.7.9` and freshly installed all python packages within a new virtualenv to the same results :cry:

**Comment by alecklandgraf** [comment]
funny enough this work

```console
$ watchmedo shell-command     --patterns="*.py;*.txt"     --recursive     --command='pt'  .
```

**Comment by skoczen** [comment]
Hey Aleck,

Thanks for the report. 

Darn.  This was a known issue that came with #4 that should have been killed with 1.1.2.  It's working here on 2.7.9, in daily driving (and py 3 fwiw.)

The problem is the mix of watchmedo and the test-runner threads.  Will dig into this as soon as I get some spare cycles, and get it fixed.  Know it's annoying to have busted!

**Comment by skoczen** [comment]
Just a quick note to say that this is being worked on, and has been replicated.  It ends up being a pretty gnarly threading problem between watchdog and the test-runner threads that's just at (or really, past) the limits of my python-fu.  

It's coming, and help is welcome!

Thanks for your patience.

**Comment by skoczen** [comment]
Work to fix this is being done on #12

**Comment by skoczen** [comment]
Hey @alecklandgraf , 

Thanks for all your patience.  The threading code for watches and test running has been rewritten, and now is working reliably in 2.7.x and 3.x.  The new release is [1.2.0](https://github.com/skoczen/polytester#120---march-6-2015).

Please give it an install, and let me know if you run in to any snags!

**Comment by alecklandgraf** [comment]
Will give it a try tomorrow. Thanks!

Aleck Landgraf
Sent from my iPhone.


On Mar 5, 2015, at 8:14 PM, Steven Skoczen <notifications@github.com> wrote:

Hey @alecklandgraf <https://github.com/alecklandgraf> ,

Thanks for all your patience. The threading code for watches and test
running has been rewritten, and now is working reliably in 2.7.x and 3.x.
The new release is 1.2.0
<https://github.com/skoczen/polytester#120---march-6-2015>.

Please give it an install, and let me know if you run in to any snags!

—
Reply to this email directly or view it on GitHub
<https://github.com/skoczen/polytester/issues/11#issuecomment-77504091>.
