### ISSUE TITLE
Karma Not Show Correct Number Of Failed Tests

### ISSUE THREAD

**Issue by jpulec** [skoczen/polytester#13]
Whenever I run karma through polytester, and a test fails, it prints:

```bash
✘ js: None of 3 tests failed.
```

It looks like this is an issue with the parsers ```num_failed()``` method and the line: 
```'Executed (\d+) of (\d+) \((\d+) FAILED\)',```

Apparently karma is outputting some ANSI escape codes (like \x1b[31m) which is being escaped by before the word 'FAILED' which is prevent the regex from matching. On a related note, it looks like the regex for ANSI stripping is in the format of a sed replacement, not a python regex, which means that escaping is experiencing other issues. I assume we actually want to strip the output and not just escape it?

**Comment by skoczen** [comment]
This is out as `1.2.1` - thanks for the contribution!
