### ISSUE TITLE
Autoreload process unkillable

### ISSUE THREAD

**Issue by joshfriend** [skoczen/polytester#4]
When I use the test runner with `--autoreload`, I am unable to terminate it, except by `kill -9`-ing the workers from another shell, or by just closing the iTerm window the reloader is running in.

Using OSX and python 2.7.9 if that matters.

**Comment by skoczen** [comment]
Hey @joshfriend , 

Thanks for the report.  Really strange.  I developed against Python 3.x, but am able to reproduce your issue here with 2.7.9.  Will have a fixed version out shortly!

-Steven

**Comment by skoczen** [comment]
Got it - 1.0.2 will go out with a fix shortly.

Thanks for raising this!

**Comment by skoczen** [comment]
[1.0.2](https://github.com/skoczen/polytester#releases) is out, and should fix this - please reopen if you still see anything odd!

**Comment by joshfriend** [comment]
Just confirming I can kill an autoreload session with 0.1.2...

**Comment by skoczen** [comment]
Fantastic - thanks for reporting back!
