### ISSUE TITLE
strip_ansi_colors() fails on various python versions

### ISSUE THREAD

**Issue by brandoncazander** [skoczen/polytester#8]
The following regex compilation from [strip_ansi_colors()](https://github.com/skoczen/polytester/blob/master/polytester/runner.py#L98) fails on some versions of python:

```python
>>> import re
>>> re.compile(r'\\x1b([^m]*)?m')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.6/re.py", line 245, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat
```

Seems to be a long-standing issue in python (matching zero-or-more of nothing), but it means that I can't use polytester on some systems.

Python 2.6.8: Fails
Python 2.7.3: Fails
Python 2.7.8: Passes
Python 3.4.1: Passes

**Comment by skoczen** [comment]
Hey @brandoncazander , thanks for the report.  Will take a look at this when I have spare cycles, but if you have a fix in the meantime, a PR is welcome!

**Comment by alecklandgraf** [comment]
yes, seeing the same thing on python 2.7.3, glad to see there's a fix already, probably time to upgrade python too

**Comment by alecklandgraf** [comment]
the patch works for on 2.7.3
